In [1]:
from sklearn import datasets

In [2]:
boston = datasets.load_boston()
X = boston.data
Y = boston.target

In [3]:
X.shape

(506, 13)

In [4]:
import pandas as pd
df = pd.DataFrame(X)
print(boston.feature_names)
df.columns = boston.feature_names
df["age_age"] = df.AGE ** 2
df.describe()
X2 = df.values
X2.shape
df

['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,age_age
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,4251.04
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,6225.21
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,3733.21
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,2097.64
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,2937.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67,4774.81
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08,5882.89
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64,8281.00
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48,7974.49
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88,6528.64

In [7]:
from sklearn import model_selection
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, Y, random_state = 0)
X2_train, X2_test, Y2_train, Y2_test = model_selection.train_test_split(X2, Y, random_state = 0)

In [8]:
from sklearn.linear_model import LinearRegression
alg1 = LinearRegression()
alg2 = LinearRegression()

In [9]:
alg1.fit(X_train, Y_train)
alg2.fit(X2_train, Y2_train)

LinearRegression()

In [10]:
Y_pred = alg1.predict(X_test)
train_score = alg1.score(X_train, Y_train)
test_score = alg1.score(X_test, Y_test)
print("Train Score: ", train_score)
print("Test Score: ", test_score)

train2_score = alg2.score(X2_train, Y2_train)
test2_score = alg2.score(X2_test, Y2_test)
print("Train2 Score: ", train2_score)
print("Test2 Score: ", test2_score)

Train Score:  0.7697699488741149
Test Score:  0.6354638433202129
Train2 Score:  0.7707245449911091
Test2 Score:  0.6433109272342966